// Mocks generated by Mockito 5.4.6 from annotations
// in avatar_maker/test/src/customizer/widgets/customizer_body_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i10;
import 'dart:ui' as _i11;

import 'package:avatar_maker/l10n/app_localizations.dart' as _i2;
import 'package:avatar_maker/src/core/controllers/avatar_maker_controller.dart'
    as _i3;
import 'package:avatar_maker/src/core/controllers/persistent_avatar_maker_controller.dart'
    as _i5;
import 'package:avatar_maker/src/core/enums/property_category_ids.dart' as _i8;
import 'package:avatar_maker/src/core/models/customized_property_category.dart'
    as _i7;
import 'package:avatar_maker/src/core/models/property_item.dart' as _i9;
import 'package:flutter/material.dart' as _i4;
import 'package:flutter/src/animation/curves.dart' as _i12;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeAppLocalizations_0 extends _i1.SmartFake
    implements _i2.AppLocalizations {
  _FakeAppLocalizations_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeRestoredData_1 extends _i1.SmartFake implements _i3.RestoredData {
  _FakeRestoredData_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDuration_2 extends _i1.SmartFake implements Duration {
  _FakeDuration_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeAnimation_3<T> extends _i1.SmartFake implements _i4.Animation<T> {
  _FakeAnimation_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeTickerFuture_4 extends _i1.SmartFake implements _i4.TickerFuture {
  _FakeTickerFuture_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [PersistentAvatarMakerController].
///
/// See the documentation for Mockito's code generation for more information.
class MockPersistentAvatarMakerController extends _i1.Mock
    implements _i5.PersistentAvatarMakerController {
  @override
  String get displayedAvatarSVG => (super.noSuchMethod(
        Invocation.getter(#displayedAvatarSVG),
        returnValue: _i6.dummyValue<String>(
          this,
          Invocation.getter(#displayedAvatarSVG),
        ),
        returnValueForMissingStub: _i6.dummyValue<String>(
          this,
          Invocation.getter(#displayedAvatarSVG),
        ),
      ) as String);

  @override
  List<_i7.CustomizedPropertyCategory> get propertyCategories =>
      (super.noSuchMethod(
        Invocation.getter(#propertyCategories),
        returnValue: <_i7.CustomizedPropertyCategory>[],
        returnValueForMissingStub: <_i7.CustomizedPropertyCategory>[],
      ) as List<_i7.CustomizedPropertyCategory>);

  @override
  List<_i7.CustomizedPropertyCategory> get displayedPropertyCategories =>
      (super.noSuchMethod(
        Invocation.getter(#displayedPropertyCategories),
        returnValue: <_i7.CustomizedPropertyCategory>[],
        returnValueForMissingStub: <_i7.CustomizedPropertyCategory>[],
      ) as List<_i7.CustomizedPropertyCategory>);

  @override
  Map<_i8.PropertyCategoryIds, _i9.PropertyItem> get defaultSelectedOptions =>
      (super.noSuchMethod(
        Invocation.getter(#defaultSelectedOptions),
        returnValue: <_i8.PropertyCategoryIds, _i9.PropertyItem>{},
        returnValueForMissingStub: <_i8.PropertyCategoryIds,
            _i9.PropertyItem>{},
      ) as Map<_i8.PropertyCategoryIds, _i9.PropertyItem>);

  @override
  _i2.AppLocalizations get l10n => (super.noSuchMethod(
        Invocation.getter(#l10n),
        returnValue: _FakeAppLocalizations_0(
          this,
          Invocation.getter(#l10n),
        ),
        returnValueForMissingStub: _FakeAppLocalizations_0(
          this,
          Invocation.getter(#l10n),
        ),
      ) as _i2.AppLocalizations);

  @override
  Map<_i8.PropertyCategoryIds, _i9.PropertyItem> get selectedOptions =>
      (super.noSuchMethod(
        Invocation.getter(#selectedOptions),
        returnValue: <_i8.PropertyCategoryIds, _i9.PropertyItem>{},
        returnValueForMissingStub: <_i8.PropertyCategoryIds,
            _i9.PropertyItem>{},
      ) as Map<_i8.PropertyCategoryIds, _i9.PropertyItem>);

  @override
  set propertyCategories(List<_i7.CustomizedPropertyCategory>? value) =>
      super.noSuchMethod(
        Invocation.setter(
          #propertyCategories,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set displayedPropertyCategories(
          List<_i7.CustomizedPropertyCategory>? value) =>
      super.noSuchMethod(
        Invocation.setter(
          #displayedPropertyCategories,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set defaultSelectedOptions(
          Map<_i8.PropertyCategoryIds, _i9.PropertyItem>? value) =>
      super.noSuchMethod(
        Invocation.setter(
          #defaultSelectedOptions,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set l10n(_i2.AppLocalizations? value) => super.noSuchMethod(
        Invocation.setter(
          #l10n,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set selectedOptions(Map<_i8.PropertyCategoryIds, _i9.PropertyItem>? value) =>
      super.noSuchMethod(
        Invocation.setter(
          #selectedOptions,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  _i10.Future<
      Map<_i8.PropertyCategoryIds,
          _i9.PropertyItem>> getSelectedOptions() => (super.noSuchMethod(
        Invocation.method(
          #getSelectedOptions,
          [],
        ),
        returnValue:
            _i10.Future<Map<_i8.PropertyCategoryIds, _i9.PropertyItem>>.value(
                <_i8.PropertyCategoryIds, _i9.PropertyItem>{}),
        returnValueForMissingStub:
            _i10.Future<Map<_i8.PropertyCategoryIds, _i9.PropertyItem>>.value(
                <_i8.PropertyCategoryIds, _i9.PropertyItem>{}),
      ) as _i10.Future<Map<_i8.PropertyCategoryIds, _i9.PropertyItem>>);

  @override
  _i10.Future<
      Map<_i8.PropertyCategoryIds,
          _i9.PropertyItem>> getStoredOptions() => (super.noSuchMethod(
        Invocation.method(
          #getStoredOptions,
          [],
        ),
        returnValue:
            _i10.Future<Map<_i8.PropertyCategoryIds, _i9.PropertyItem>>.value(
                <_i8.PropertyCategoryIds, _i9.PropertyItem>{}),
        returnValueForMissingStub:
            _i10.Future<Map<_i8.PropertyCategoryIds, _i9.PropertyItem>>.value(
                <_i8.PropertyCategoryIds, _i9.PropertyItem>{}),
      ) as _i10.Future<Map<_i8.PropertyCategoryIds, _i9.PropertyItem>>);

  @override
  _i10.Future<String> save() => (super.noSuchMethod(
        Invocation.method(
          #save,
          [],
        ),
        returnValue: _i10.Future<String>.value(_i6.dummyValue<String>(
          this,
          Invocation.method(
            #save,
            [],
          ),
        )),
        returnValueForMissingStub:
            _i10.Future<String>.value(_i6.dummyValue<String>(
          this,
          Invocation.method(
            #save,
            [],
          ),
        )),
      ) as _i10.Future<String>);

  @override
  _i10.Future<_i3.RestoredData> performRestore() => (super.noSuchMethod(
        Invocation.method(
          #performRestore,
          [],
        ),
        returnValue: _i10.Future<_i3.RestoredData>.value(_FakeRestoredData_1(
          this,
          Invocation.method(
            #performRestore,
            [],
          ),
        )),
        returnValueForMissingStub:
            _i10.Future<_i3.RestoredData>.value(_FakeRestoredData_1(
          this,
          Invocation.method(
            #performRestore,
            [],
          ),
        )),
      ) as _i10.Future<_i3.RestoredData>);

  @override
  bool isPersistentController() => (super.noSuchMethod(
        Invocation.method(
          #isPersistentController,
          [],
        ),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  _i10.Future<void> initController() => (super.noSuchMethod(
        Invocation.method(
          #initController,
          [],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  void updatePreview({String? newAvatarMakerSVG = ''}) => super.noSuchMethod(
        Invocation.method(
          #updatePreview,
          [],
          {#newAvatarMakerSVG: newAvatarMakerSVG},
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i10.Future<void> saveAvatarSVG({String? jsonAvatarOptions}) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveAvatarSVG,
          [],
          {#jsonAvatarOptions: jsonAvatarOptions},
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> restoreState() => (super.noSuchMethod(
        Invocation.method(
          #restoreState,
          [],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  String drawAvatarSVG() => (super.noSuchMethod(
        Invocation.method(
          #drawAvatarSVG,
          [],
        ),
        returnValue: _i6.dummyValue<String>(
          this,
          Invocation.method(
            #drawAvatarSVG,
            [],
          ),
        ),
        returnValueForMissingStub: _i6.dummyValue<String>(
          this,
          Invocation.method(
            #drawAvatarSVG,
            [],
          ),
        ),
      ) as String);

  @override
  String getComponentSVG(
    _i8.PropertyCategoryIds? categoryId,
    int? index,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getComponentSVG,
          [
            categoryId,
            index,
          ],
        ),
        returnValue: _i6.dummyValue<String>(
          this,
          Invocation.method(
            #getComponentSVG,
            [
              categoryId,
              index,
            ],
          ),
        ),
        returnValueForMissingStub: _i6.dummyValue<String>(
          this,
          Invocation.method(
            #getComponentSVG,
            [
              categoryId,
              index,
            ],
          ),
        ),
      ) as String);

  @override
  void randomizedSelectedOptions() => super.noSuchMethod(
        Invocation.method(
          #randomizedSelectedOptions,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  String getJsonOptionsSync() => (super.noSuchMethod(
        Invocation.method(
          #getJsonOptionsSync,
          [],
        ),
        returnValue: _i6.dummyValue<String>(
          this,
          Invocation.method(
            #getJsonOptionsSync,
            [],
          ),
        ),
        returnValueForMissingStub: _i6.dummyValue<String>(
          this,
          Invocation.method(
            #getJsonOptionsSync,
            [],
          ),
        ),
      ) as String);

  @override
  String getAvatarSVGSync() => (super.noSuchMethod(
        Invocation.method(
          #getAvatarSVGSync,
          [],
        ),
        returnValue: _i6.dummyValue<String>(
          this,
          Invocation.method(
            #getAvatarSVGSync,
            [],
          ),
        ),
        returnValueForMissingStub: _i6.dummyValue<String>(
          this,
          Invocation.method(
            #getAvatarSVGSync,
            [],
          ),
        ),
      ) as String);

  @override
  void addListener(_i11.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i11.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [TabController].
///
/// See the documentation for Mockito's code generation for more information.
class MockTabController extends _i1.Mock implements _i4.TabController {
  @override
  Duration get animationDuration => (super.noSuchMethod(
        Invocation.getter(#animationDuration),
        returnValue: _FakeDuration_2(
          this,
          Invocation.getter(#animationDuration),
        ),
        returnValueForMissingStub: _FakeDuration_2(
          this,
          Invocation.getter(#animationDuration),
        ),
      ) as Duration);

  @override
  int get length => (super.noSuchMethod(
        Invocation.getter(#length),
        returnValue: 0,
        returnValueForMissingStub: 0,
      ) as int);

  @override
  int get index => (super.noSuchMethod(
        Invocation.getter(#index),
        returnValue: 0,
        returnValueForMissingStub: 0,
      ) as int);

  @override
  int get previousIndex => (super.noSuchMethod(
        Invocation.getter(#previousIndex),
        returnValue: 0,
        returnValueForMissingStub: 0,
      ) as int);

  @override
  bool get indexIsChanging => (super.noSuchMethod(
        Invocation.getter(#indexIsChanging),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  double get offset => (super.noSuchMethod(
        Invocation.getter(#offset),
        returnValue: 0.0,
        returnValueForMissingStub: 0.0,
      ) as double);

  @override
  set index(int? value) => super.noSuchMethod(
        Invocation.setter(
          #index,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set offset(double? value) => super.noSuchMethod(
        Invocation.setter(
          #offset,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  void animateTo(
    int? value, {
    Duration? duration,
    _i4.Curve? curve = _i4.Curves.ease,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #animateTo,
          [value],
          {
            #duration: duration,
            #curve: curve,
          },
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addListener(_i11.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i11.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [AnimationController].
///
/// See the documentation for Mockito's code generation for more information.
class MockAnimationController extends _i1.Mock
    implements _i4.AnimationController {
  @override
  double get lowerBound => (super.noSuchMethod(
        Invocation.getter(#lowerBound),
        returnValue: 0.0,
        returnValueForMissingStub: 0.0,
      ) as double);

  @override
  double get upperBound => (super.noSuchMethod(
        Invocation.getter(#upperBound),
        returnValue: 0.0,
        returnValueForMissingStub: 0.0,
      ) as double);

  @override
  _i4.AnimationBehavior get animationBehavior => (super.noSuchMethod(
        Invocation.getter(#animationBehavior),
        returnValue: _i4.AnimationBehavior.normal,
        returnValueForMissingStub: _i4.AnimationBehavior.normal,
      ) as _i4.AnimationBehavior);

  @override
  _i4.Animation<double> get view => (super.noSuchMethod(
        Invocation.getter(#view),
        returnValue: _FakeAnimation_3<double>(
          this,
          Invocation.getter(#view),
        ),
        returnValueForMissingStub: _FakeAnimation_3<double>(
          this,
          Invocation.getter(#view),
        ),
      ) as _i4.Animation<double>);

  @override
  double get value => (super.noSuchMethod(
        Invocation.getter(#value),
        returnValue: 0.0,
        returnValueForMissingStub: 0.0,
      ) as double);

  @override
  double get velocity => (super.noSuchMethod(
        Invocation.getter(#velocity),
        returnValue: 0.0,
        returnValueForMissingStub: 0.0,
      ) as double);

  @override
  bool get isAnimating => (super.noSuchMethod(
        Invocation.getter(#isAnimating),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  _i4.AnimationStatus get status => (super.noSuchMethod(
        Invocation.getter(#status),
        returnValue: _i4.AnimationStatus.dismissed,
        returnValueForMissingStub: _i4.AnimationStatus.dismissed,
      ) as _i4.AnimationStatus);

  @override
  set duration(Duration? value) => super.noSuchMethod(
        Invocation.setter(
          #duration,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set reverseDuration(Duration? value) => super.noSuchMethod(
        Invocation.setter(
          #reverseDuration,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set value(double? newValue) => super.noSuchMethod(
        Invocation.setter(
          #value,
          newValue,
        ),
        returnValueForMissingStub: null,
      );

  @override
  bool get isDismissed => (super.noSuchMethod(
        Invocation.getter(#isDismissed),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get isCompleted => (super.noSuchMethod(
        Invocation.getter(#isCompleted),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get isForwardOrCompleted => (super.noSuchMethod(
        Invocation.getter(#isForwardOrCompleted),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  void resync(_i4.TickerProvider? vsync) => super.noSuchMethod(
        Invocation.method(
          #resync,
          [vsync],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void reset() => super.noSuchMethod(
        Invocation.method(
          #reset,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i4.TickerFuture forward({double? from}) => (super.noSuchMethod(
        Invocation.method(
          #forward,
          [],
          {#from: from},
        ),
        returnValue: _FakeTickerFuture_4(
          this,
          Invocation.method(
            #forward,
            [],
            {#from: from},
          ),
        ),
        returnValueForMissingStub: _FakeTickerFuture_4(
          this,
          Invocation.method(
            #forward,
            [],
            {#from: from},
          ),
        ),
      ) as _i4.TickerFuture);

  @override
  _i4.TickerFuture reverse({double? from}) => (super.noSuchMethod(
        Invocation.method(
          #reverse,
          [],
          {#from: from},
        ),
        returnValue: _FakeTickerFuture_4(
          this,
          Invocation.method(
            #reverse,
            [],
            {#from: from},
          ),
        ),
        returnValueForMissingStub: _FakeTickerFuture_4(
          this,
          Invocation.method(
            #reverse,
            [],
            {#from: from},
          ),
        ),
      ) as _i4.TickerFuture);

  @override
  _i4.TickerFuture toggle({double? from}) => (super.noSuchMethod(
        Invocation.method(
          #toggle,
          [],
          {#from: from},
        ),
        returnValue: _FakeTickerFuture_4(
          this,
          Invocation.method(
            #toggle,
            [],
            {#from: from},
          ),
        ),
        returnValueForMissingStub: _FakeTickerFuture_4(
          this,
          Invocation.method(
            #toggle,
            [],
            {#from: from},
          ),
        ),
      ) as _i4.TickerFuture);

  @override
  _i4.TickerFuture animateTo(
    double? target, {
    Duration? duration,
    _i4.Curve? curve = _i12.Curves.linear,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #animateTo,
          [target],
          {
            #duration: duration,
            #curve: curve,
          },
        ),
        returnValue: _FakeTickerFuture_4(
          this,
          Invocation.method(
            #animateTo,
            [target],
            {
              #duration: duration,
              #curve: curve,
            },
          ),
        ),
        returnValueForMissingStub: _FakeTickerFuture_4(
          this,
          Invocation.method(
            #animateTo,
            [target],
            {
              #duration: duration,
              #curve: curve,
            },
          ),
        ),
      ) as _i4.TickerFuture);

  @override
  _i4.TickerFuture animateBack(
    double? target, {
    Duration? duration,
    _i4.Curve? curve = _i12.Curves.linear,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #animateBack,
          [target],
          {
            #duration: duration,
            #curve: curve,
          },
        ),
        returnValue: _FakeTickerFuture_4(
          this,
          Invocation.method(
            #animateBack,
            [target],
            {
              #duration: duration,
              #curve: curve,
            },
          ),
        ),
        returnValueForMissingStub: _FakeTickerFuture_4(
          this,
          Invocation.method(
            #animateBack,
            [target],
            {
              #duration: duration,
              #curve: curve,
            },
          ),
        ),
      ) as _i4.TickerFuture);

  @override
  _i4.TickerFuture repeat({
    double? min,
    double? max,
    bool? reverse = false,
    Duration? period,
    int? count,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #repeat,
          [],
          {
            #min: min,
            #max: max,
            #reverse: reverse,
            #period: period,
            #count: count,
          },
        ),
        returnValue: _FakeTickerFuture_4(
          this,
          Invocation.method(
            #repeat,
            [],
            {
              #min: min,
              #max: max,
              #reverse: reverse,
              #period: period,
              #count: count,
            },
          ),
        ),
        returnValueForMissingStub: _FakeTickerFuture_4(
          this,
          Invocation.method(
            #repeat,
            [],
            {
              #min: min,
              #max: max,
              #reverse: reverse,
              #period: period,
              #count: count,
            },
          ),
        ),
      ) as _i4.TickerFuture);

  @override
  _i4.TickerFuture fling({
    double? velocity = 1.0,
    _i4.SpringDescription? springDescription,
    _i4.AnimationBehavior? animationBehavior,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #fling,
          [],
          {
            #velocity: velocity,
            #springDescription: springDescription,
            #animationBehavior: animationBehavior,
          },
        ),
        returnValue: _FakeTickerFuture_4(
          this,
          Invocation.method(
            #fling,
            [],
            {
              #velocity: velocity,
              #springDescription: springDescription,
              #animationBehavior: animationBehavior,
            },
          ),
        ),
        returnValueForMissingStub: _FakeTickerFuture_4(
          this,
          Invocation.method(
            #fling,
            [],
            {
              #velocity: velocity,
              #springDescription: springDescription,
              #animationBehavior: animationBehavior,
            },
          ),
        ),
      ) as _i4.TickerFuture);

  @override
  _i4.TickerFuture animateWith(_i4.Simulation? simulation) =>
      (super.noSuchMethod(
        Invocation.method(
          #animateWith,
          [simulation],
        ),
        returnValue: _FakeTickerFuture_4(
          this,
          Invocation.method(
            #animateWith,
            [simulation],
          ),
        ),
        returnValueForMissingStub: _FakeTickerFuture_4(
          this,
          Invocation.method(
            #animateWith,
            [simulation],
          ),
        ),
      ) as _i4.TickerFuture);

  @override
  _i4.TickerFuture animateBackWith(_i4.Simulation? simulation) =>
      (super.noSuchMethod(
        Invocation.method(
          #animateBackWith,
          [simulation],
        ),
        returnValue: _FakeTickerFuture_4(
          this,
          Invocation.method(
            #animateBackWith,
            [simulation],
          ),
        ),
        returnValueForMissingStub: _FakeTickerFuture_4(
          this,
          Invocation.method(
            #animateBackWith,
            [simulation],
          ),
        ),
      ) as _i4.TickerFuture);

  @override
  void stop({bool? canceled = true}) => super.noSuchMethod(
        Invocation.method(
          #stop,
          [],
          {#canceled: canceled},
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  String toStringDetails() => (super.noSuchMethod(
        Invocation.method(
          #toStringDetails,
          [],
        ),
        returnValue: _i6.dummyValue<String>(
          this,
          Invocation.method(
            #toStringDetails,
            [],
          ),
        ),
        returnValueForMissingStub: _i6.dummyValue<String>(
          this,
          Invocation.method(
            #toStringDetails,
            [],
          ),
        ),
      ) as String);

  @override
  void addListener(_i11.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i11.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addStatusListener(_i4.AnimationStatusListener? listener) =>
      super.noSuchMethod(
        Invocation.method(
          #addStatusListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeStatusListener(_i4.AnimationStatusListener? listener) =>
      super.noSuchMethod(
        Invocation.method(
          #removeStatusListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i4.Animation<U> drive<U>(_i4.Animatable<U>? child) => (super.noSuchMethod(
        Invocation.method(
          #drive,
          [child],
        ),
        returnValue: _FakeAnimation_3<U>(
          this,
          Invocation.method(
            #drive,
            [child],
          ),
        ),
        returnValueForMissingStub: _FakeAnimation_3<U>(
          this,
          Invocation.method(
            #drive,
            [child],
          ),
        ),
      ) as _i4.Animation<U>);

  @override
  void didRegisterListener() => super.noSuchMethod(
        Invocation.method(
          #didRegisterListener,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void didUnregisterListener() => super.noSuchMethod(
        Invocation.method(
          #didUnregisterListener,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void clearListeners() => super.noSuchMethod(
        Invocation.method(
          #clearListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void clearStatusListeners() => super.noSuchMethod(
        Invocation.method(
          #clearStatusListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyStatusListeners(_i4.AnimationStatus? status) => super.noSuchMethod(
        Invocation.method(
          #notifyStatusListeners,
          [status],
        ),
        returnValueForMissingStub: null,
      );
}
