arb-dir: localization
output-dir: lib/l10n
template-arb-file: en.arb
output-localization-file: app_localizations.dart
nullable-getter: false
untranslated-messages-file: untranslated-messages.txt
synthetic-package: false