// Mocks generated by Mockito 5.4.6 from annotations
// in avatar_maker/test/src/customizer/avatar_maker_random_widget_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i9;
import 'dart:ui' as _i10;

import 'package:avatar_maker/l10n/app_localizations.dart' as _i2;
import 'package:avatar_maker/src/core/controllers/avatar_maker_controller.dart'
    as _i3;
import 'package:avatar_maker/src/core/controllers/persistent_avatar_maker_controller.dart'
    as _i4;
import 'package:avatar_maker/src/core/enums/property_category_ids.dart' as _i7;
import 'package:avatar_maker/src/core/models/customized_property_category.dart'
    as _i6;
import 'package:avatar_maker/src/core/models/property_item.dart' as _i8;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeAppLocalizations_0 extends _i1.SmartFake
    implements _i2.AppLocalizations {
  _FakeAppLocalizations_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeRestoredData_1 extends _i1.SmartFake implements _i3.RestoredData {
  _FakeRestoredData_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [PersistentAvatarMakerController].
///
/// See the documentation for Mockito's code generation for more information.
class MockPersistentAvatarMakerController extends _i1.Mock
    implements _i4.PersistentAvatarMakerController {
  @override
  String get displayedAvatarSVG => (super.noSuchMethod(
        Invocation.getter(#displayedAvatarSVG),
        returnValue: _i5.dummyValue<String>(
          this,
          Invocation.getter(#displayedAvatarSVG),
        ),
        returnValueForMissingStub: _i5.dummyValue<String>(
          this,
          Invocation.getter(#displayedAvatarSVG),
        ),
      ) as String);

  @override
  List<_i6.CustomizedPropertyCategory> get propertyCategories =>
      (super.noSuchMethod(
        Invocation.getter(#propertyCategories),
        returnValue: <_i6.CustomizedPropertyCategory>[],
        returnValueForMissingStub: <_i6.CustomizedPropertyCategory>[],
      ) as List<_i6.CustomizedPropertyCategory>);

  @override
  List<_i6.CustomizedPropertyCategory> get displayedPropertyCategories =>
      (super.noSuchMethod(
        Invocation.getter(#displayedPropertyCategories),
        returnValue: <_i6.CustomizedPropertyCategory>[],
        returnValueForMissingStub: <_i6.CustomizedPropertyCategory>[],
      ) as List<_i6.CustomizedPropertyCategory>);

  @override
  Map<_i7.PropertyCategoryIds, _i8.PropertyItem> get defaultSelectedOptions =>
      (super.noSuchMethod(
        Invocation.getter(#defaultSelectedOptions),
        returnValue: <_i7.PropertyCategoryIds, _i8.PropertyItem>{},
        returnValueForMissingStub: <_i7.PropertyCategoryIds,
            _i8.PropertyItem>{},
      ) as Map<_i7.PropertyCategoryIds, _i8.PropertyItem>);

  @override
  _i2.AppLocalizations get l10n => (super.noSuchMethod(
        Invocation.getter(#l10n),
        returnValue: _FakeAppLocalizations_0(
          this,
          Invocation.getter(#l10n),
        ),
        returnValueForMissingStub: _FakeAppLocalizations_0(
          this,
          Invocation.getter(#l10n),
        ),
      ) as _i2.AppLocalizations);

  @override
  Map<_i7.PropertyCategoryIds, _i8.PropertyItem> get selectedOptions =>
      (super.noSuchMethod(
        Invocation.getter(#selectedOptions),
        returnValue: <_i7.PropertyCategoryIds, _i8.PropertyItem>{},
        returnValueForMissingStub: <_i7.PropertyCategoryIds,
            _i8.PropertyItem>{},
      ) as Map<_i7.PropertyCategoryIds, _i8.PropertyItem>);

  @override
  set propertyCategories(List<_i6.CustomizedPropertyCategory>? value) =>
      super.noSuchMethod(
        Invocation.setter(
          #propertyCategories,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set displayedPropertyCategories(
          List<_i6.CustomizedPropertyCategory>? value) =>
      super.noSuchMethod(
        Invocation.setter(
          #displayedPropertyCategories,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set defaultSelectedOptions(
          Map<_i7.PropertyCategoryIds, _i8.PropertyItem>? value) =>
      super.noSuchMethod(
        Invocation.setter(
          #defaultSelectedOptions,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set l10n(_i2.AppLocalizations? value) => super.noSuchMethod(
        Invocation.setter(
          #l10n,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set selectedOptions(Map<_i7.PropertyCategoryIds, _i8.PropertyItem>? value) =>
      super.noSuchMethod(
        Invocation.setter(
          #selectedOptions,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  _i9.Future<
      Map<_i7.PropertyCategoryIds,
          _i8.PropertyItem>> getSelectedOptions() => (super.noSuchMethod(
        Invocation.method(
          #getSelectedOptions,
          [],
        ),
        returnValue:
            _i9.Future<Map<_i7.PropertyCategoryIds, _i8.PropertyItem>>.value(
                <_i7.PropertyCategoryIds, _i8.PropertyItem>{}),
        returnValueForMissingStub:
            _i9.Future<Map<_i7.PropertyCategoryIds, _i8.PropertyItem>>.value(
                <_i7.PropertyCategoryIds, _i8.PropertyItem>{}),
      ) as _i9.Future<Map<_i7.PropertyCategoryIds, _i8.PropertyItem>>);

  @override
  _i9.Future<
      Map<_i7.PropertyCategoryIds,
          _i8.PropertyItem>> getStoredOptions() => (super.noSuchMethod(
        Invocation.method(
          #getStoredOptions,
          [],
        ),
        returnValue:
            _i9.Future<Map<_i7.PropertyCategoryIds, _i8.PropertyItem>>.value(
                <_i7.PropertyCategoryIds, _i8.PropertyItem>{}),
        returnValueForMissingStub:
            _i9.Future<Map<_i7.PropertyCategoryIds, _i8.PropertyItem>>.value(
                <_i7.PropertyCategoryIds, _i8.PropertyItem>{}),
      ) as _i9.Future<Map<_i7.PropertyCategoryIds, _i8.PropertyItem>>);

  @override
  _i9.Future<String> save() => (super.noSuchMethod(
        Invocation.method(
          #save,
          [],
        ),
        returnValue: _i9.Future<String>.value(_i5.dummyValue<String>(
          this,
          Invocation.method(
            #save,
            [],
          ),
        )),
        returnValueForMissingStub:
            _i9.Future<String>.value(_i5.dummyValue<String>(
          this,
          Invocation.method(
            #save,
            [],
          ),
        )),
      ) as _i9.Future<String>);

  @override
  _i9.Future<_i3.RestoredData> performRestore() => (super.noSuchMethod(
        Invocation.method(
          #performRestore,
          [],
        ),
        returnValue: _i9.Future<_i3.RestoredData>.value(_FakeRestoredData_1(
          this,
          Invocation.method(
            #performRestore,
            [],
          ),
        )),
        returnValueForMissingStub:
            _i9.Future<_i3.RestoredData>.value(_FakeRestoredData_1(
          this,
          Invocation.method(
            #performRestore,
            [],
          ),
        )),
      ) as _i9.Future<_i3.RestoredData>);

  @override
  bool isPersistentController() => (super.noSuchMethod(
        Invocation.method(
          #isPersistentController,
          [],
        ),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  _i9.Future<void> initController() => (super.noSuchMethod(
        Invocation.method(
          #initController,
          [],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  void updatePreview({String? newAvatarMakerSVG = ''}) => super.noSuchMethod(
        Invocation.method(
          #updatePreview,
          [],
          {#newAvatarMakerSVG: newAvatarMakerSVG},
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i9.Future<void> saveAvatarSVG({String? jsonAvatarOptions}) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveAvatarSVG,
          [],
          {#jsonAvatarOptions: jsonAvatarOptions},
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<void> restoreState() => (super.noSuchMethod(
        Invocation.method(
          #restoreState,
          [],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  String drawAvatarSVG() => (super.noSuchMethod(
        Invocation.method(
          #drawAvatarSVG,
          [],
        ),
        returnValue: _i5.dummyValue<String>(
          this,
          Invocation.method(
            #drawAvatarSVG,
            [],
          ),
        ),
        returnValueForMissingStub: _i5.dummyValue<String>(
          this,
          Invocation.method(
            #drawAvatarSVG,
            [],
          ),
        ),
      ) as String);

  @override
  String getComponentSVG(
    _i7.PropertyCategoryIds? categoryId,
    int? index,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getComponentSVG,
          [
            categoryId,
            index,
          ],
        ),
        returnValue: _i5.dummyValue<String>(
          this,
          Invocation.method(
            #getComponentSVG,
            [
              categoryId,
              index,
            ],
          ),
        ),
        returnValueForMissingStub: _i5.dummyValue<String>(
          this,
          Invocation.method(
            #getComponentSVG,
            [
              categoryId,
              index,
            ],
          ),
        ),
      ) as String);

  @override
  void randomizedSelectedOptions() => super.noSuchMethod(
        Invocation.method(
          #randomizedSelectedOptions,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  String getJsonOptionsSync() => (super.noSuchMethod(
        Invocation.method(
          #getJsonOptionsSync,
          [],
        ),
        returnValue: _i5.dummyValue<String>(
          this,
          Invocation.method(
            #getJsonOptionsSync,
            [],
          ),
        ),
        returnValueForMissingStub: _i5.dummyValue<String>(
          this,
          Invocation.method(
            #getJsonOptionsSync,
            [],
          ),
        ),
      ) as String);

  @override
  String getAvatarSVGSync() => (super.noSuchMethod(
        Invocation.method(
          #getAvatarSVGSync,
          [],
        ),
        returnValue: _i5.dummyValue<String>(
          this,
          Invocation.method(
            #getAvatarSVGSync,
            [],
          ),
        ),
        returnValueForMissingStub: _i5.dummyValue<String>(
          this,
          Invocation.method(
            #getAvatarSVGSync,
            [],
          ),
        ),
      ) as String);

  @override
  void addListener(_i10.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i10.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
