const String TO_REPLACE_WITH_CLOTHES_COLOR = "TO_REPLACE_WITH_CLOTHES_COLOR";
const String TO_REPLACE_WITH_FACIAL_HAIRS_COLOR = "TO_REPLACE_WITH_FACIAL_HAIRS_COLOR";
const String TO_REPLACE_WITH_HAIRS_COLOR = "TO_REPLACE_WITH_HAIRS_COLOR";