// Mocks generated by Mockito 5.4.6 from annotations
// in avatar_maker/test/src/core/providers/avatar_maker_controller_provider_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i8;
import 'dart:ui' as _i9;

import 'package:avatar_maker/l10n/app_localizations.dart' as _i2;
import 'package:avatar_maker/src/core/controllers/avatar_maker_controller.dart'
    as _i3;
import 'package:avatar_maker/src/core/enums/property_category_ids.dart' as _i5;
import 'package:avatar_maker/src/core/models/customized_property_category.dart'
    as _i4;
import 'package:avatar_maker/src/core/models/property_item.dart' as _i6;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeAppLocalizations_0 extends _i1.SmartFake
    implements _i2.AppLocalizations {
  _FakeAppLocalizations_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeRestoredData_1 extends _i1.SmartFake implements _i3.RestoredData {
  _FakeRestoredData_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [AvatarMakerController].
///
/// See the documentation for Mockito's code generation for more information.
class MockAvatarMakerController extends _i1.Mock
    implements _i3.AvatarMakerController {
  @override
  List<_i4.CustomizedPropertyCategory> get propertyCategories =>
      (super.noSuchMethod(
        Invocation.getter(#propertyCategories),
        returnValue: <_i4.CustomizedPropertyCategory>[],
        returnValueForMissingStub: <_i4.CustomizedPropertyCategory>[],
      ) as List<_i4.CustomizedPropertyCategory>);

  @override
  List<_i4.CustomizedPropertyCategory> get displayedPropertyCategories =>
      (super.noSuchMethod(
        Invocation.getter(#displayedPropertyCategories),
        returnValue: <_i4.CustomizedPropertyCategory>[],
        returnValueForMissingStub: <_i4.CustomizedPropertyCategory>[],
      ) as List<_i4.CustomizedPropertyCategory>);

  @override
  Map<_i5.PropertyCategoryIds, _i6.PropertyItem> get defaultSelectedOptions =>
      (super.noSuchMethod(
        Invocation.getter(#defaultSelectedOptions),
        returnValue: <_i5.PropertyCategoryIds, _i6.PropertyItem>{},
        returnValueForMissingStub: <_i5.PropertyCategoryIds,
            _i6.PropertyItem>{},
      ) as Map<_i5.PropertyCategoryIds, _i6.PropertyItem>);

  @override
  _i2.AppLocalizations get l10n => (super.noSuchMethod(
        Invocation.getter(#l10n),
        returnValue: _FakeAppLocalizations_0(
          this,
          Invocation.getter(#l10n),
        ),
        returnValueForMissingStub: _FakeAppLocalizations_0(
          this,
          Invocation.getter(#l10n),
        ),
      ) as _i2.AppLocalizations);

  @override
  Map<_i5.PropertyCategoryIds, _i6.PropertyItem> get selectedOptions =>
      (super.noSuchMethod(
        Invocation.getter(#selectedOptions),
        returnValue: <_i5.PropertyCategoryIds, _i6.PropertyItem>{},
        returnValueForMissingStub: <_i5.PropertyCategoryIds,
            _i6.PropertyItem>{},
      ) as Map<_i5.PropertyCategoryIds, _i6.PropertyItem>);

  @override
  String get displayedAvatarSVG => (super.noSuchMethod(
        Invocation.getter(#displayedAvatarSVG),
        returnValue: _i7.dummyValue<String>(
          this,
          Invocation.getter(#displayedAvatarSVG),
        ),
        returnValueForMissingStub: _i7.dummyValue<String>(
          this,
          Invocation.getter(#displayedAvatarSVG),
        ),
      ) as String);

  @override
  set propertyCategories(
          List<_i4.CustomizedPropertyCategory>? _propertyCategories) =>
      super.noSuchMethod(
        Invocation.setter(
          #propertyCategories,
          _propertyCategories,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set displayedPropertyCategories(
          List<_i4.CustomizedPropertyCategory>? _displayedPropertyCategories) =>
      super.noSuchMethod(
        Invocation.setter(
          #displayedPropertyCategories,
          _displayedPropertyCategories,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set defaultSelectedOptions(
          Map<_i5.PropertyCategoryIds, _i6.PropertyItem>?
              _defaultSelectedOptions) =>
      super.noSuchMethod(
        Invocation.setter(
          #defaultSelectedOptions,
          _defaultSelectedOptions,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set l10n(_i2.AppLocalizations? _l10n) => super.noSuchMethod(
        Invocation.setter(
          #l10n,
          _l10n,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set selectedOptions(
          Map<_i5.PropertyCategoryIds, _i6.PropertyItem>? _selectedOptions) =>
      super.noSuchMethod(
        Invocation.setter(
          #selectedOptions,
          _selectedOptions,
        ),
        returnValueForMissingStub: null,
      );

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  _i8.Future<void> initController() => (super.noSuchMethod(
        Invocation.method(
          #initController,
          [],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<
      Map<_i5.PropertyCategoryIds,
          _i6.PropertyItem>> getSelectedOptions() => (super.noSuchMethod(
        Invocation.method(
          #getSelectedOptions,
          [],
        ),
        returnValue:
            _i8.Future<Map<_i5.PropertyCategoryIds, _i6.PropertyItem>>.value(
                <_i5.PropertyCategoryIds, _i6.PropertyItem>{}),
        returnValueForMissingStub:
            _i8.Future<Map<_i5.PropertyCategoryIds, _i6.PropertyItem>>.value(
                <_i5.PropertyCategoryIds, _i6.PropertyItem>{}),
      ) as _i8.Future<Map<_i5.PropertyCategoryIds, _i6.PropertyItem>>);

  @override
  void updatePreview({String? newAvatarMakerSVG = ''}) => super.noSuchMethod(
        Invocation.method(
          #updatePreview,
          [],
          {#newAvatarMakerSVG: newAvatarMakerSVG},
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i8.Future<void> saveAvatarSVG({String? jsonAvatarOptions}) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveAvatarSVG,
          [],
          {#jsonAvatarOptions: jsonAvatarOptions},
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<String> save() => (super.noSuchMethod(
        Invocation.method(
          #save,
          [],
        ),
        returnValue: _i8.Future<String>.value(_i7.dummyValue<String>(
          this,
          Invocation.method(
            #save,
            [],
          ),
        )),
        returnValueForMissingStub:
            _i8.Future<String>.value(_i7.dummyValue<String>(
          this,
          Invocation.method(
            #save,
            [],
          ),
        )),
      ) as _i8.Future<String>);

  @override
  _i8.Future<void> restoreState() => (super.noSuchMethod(
        Invocation.method(
          #restoreState,
          [],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<_i3.RestoredData> performRestore() => (super.noSuchMethod(
        Invocation.method(
          #performRestore,
          [],
        ),
        returnValue: _i8.Future<_i3.RestoredData>.value(_FakeRestoredData_1(
          this,
          Invocation.method(
            #performRestore,
            [],
          ),
        )),
        returnValueForMissingStub:
            _i8.Future<_i3.RestoredData>.value(_FakeRestoredData_1(
          this,
          Invocation.method(
            #performRestore,
            [],
          ),
        )),
      ) as _i8.Future<_i3.RestoredData>);

  @override
  String drawAvatarSVG() => (super.noSuchMethod(
        Invocation.method(
          #drawAvatarSVG,
          [],
        ),
        returnValue: _i7.dummyValue<String>(
          this,
          Invocation.method(
            #drawAvatarSVG,
            [],
          ),
        ),
        returnValueForMissingStub: _i7.dummyValue<String>(
          this,
          Invocation.method(
            #drawAvatarSVG,
            [],
          ),
        ),
      ) as String);

  @override
  String getComponentSVG(
    _i5.PropertyCategoryIds? categoryId,
    int? index,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getComponentSVG,
          [
            categoryId,
            index,
          ],
        ),
        returnValue: _i7.dummyValue<String>(
          this,
          Invocation.method(
            #getComponentSVG,
            [
              categoryId,
              index,
            ],
          ),
        ),
        returnValueForMissingStub: _i7.dummyValue<String>(
          this,
          Invocation.method(
            #getComponentSVG,
            [
              categoryId,
              index,
            ],
          ),
        ),
      ) as String);

  @override
  void randomizedSelectedOptions() => super.noSuchMethod(
        Invocation.method(
          #randomizedSelectedOptions,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  String getJsonOptionsSync() => (super.noSuchMethod(
        Invocation.method(
          #getJsonOptionsSync,
          [],
        ),
        returnValue: _i7.dummyValue<String>(
          this,
          Invocation.method(
            #getJsonOptionsSync,
            [],
          ),
        ),
        returnValueForMissingStub: _i7.dummyValue<String>(
          this,
          Invocation.method(
            #getJsonOptionsSync,
            [],
          ),
        ),
      ) as String);

  @override
  String getAvatarSVGSync() => (super.noSuchMethod(
        Invocation.method(
          #getAvatarSVGSync,
          [],
        ),
        returnValue: _i7.dummyValue<String>(
          this,
          Invocation.method(
            #getAvatarSVGSync,
            [],
          ),
        ),
        returnValueForMissingStub: _i7.dummyValue<String>(
          this,
          Invocation.method(
            #getAvatarSVGSync,
            [],
          ),
        ),
      ) as String);

  @override
  void addListener(_i9.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i9.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
